brickstar/bike_share

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb
Implemented setup of Bulma framework
Seed database locally
Add font awesome link
=> seed database locally and import bulma for styling

Gemfile, Gemfile.lock, app/controllers/stations_controller.rb, app/models/station.rb, app/views/stations/show.html.erb, config/routes.rb, spec/features/visitors/sees_station_name_slug_and_station_attributes_spec.rb
__X__ Wrote Tests __X__ Implemented ____ Reviewed
##Closes Waffle Issue #2  
[] Bug Fix
Checklist:
Link: https://vine.co/v/5hraxvIqJJu
=> Visitor station show

.rspec, app/controllers/stations_controller.rb, app/views/stations/index.html.erb, config/routes.rb, spec/features/visitors/sees_all_stations_spec.rb
Wrote Test & Implement
##Closes Waffle Issue #1  
[] Bug Fix
Checklist:
[x] I have commented my code, particularly in hard-to-understand areas
Link: https://channongray.com/wp-content/uploads/2015/07/54611478.jpg
=> add feature test for stations index

app/controllers/conditions_controller.rb, app/views/conditions/index.html.erb, config/routes.rb, spec/features/visitors/sees_all_conditions_spec.rb
XWrote Tests XImplemented ____ Reviewed
##Closes Waffle Issue #6 
[] Bug Fix
Checklist:
[x] I have commented my code, particularly in hard-to-understand areas
Link:
=> Visitor conditions index

app/views/trips/index.html.erb, spec/features/visitors/sees_all_trips_spec.rb
XWrote Tests X Implemented ____ Reviewed
##Closes Waffle Issue #4 
[] Bug Fix
[X] Some Tests have been changed- Trips index page test now looks at Bike ID instead of duration
Checklist:
Link: next time!
=> Visitor trips index b

app/controllers/conditions_controller.rb, app/views/conditions/show.html.erb, config/routes.rb, db/migrate/20180721192437_create_friendly_id_slugs.rb, db/migrate/20180721202803_add_slug_to_stations.rb, spec/features/visitors/sees_attributes_on_condition_show_spec.rb
__x__ Wrote Tests __x__ Implemented __x__ Reviewed
##Closes Waffle Issue #7 
[] Bug Fix
Checklist:
Link:  https://giphy.com/gifs/easy-covergirl-mootiful-eW3QwuAfmpGne
=> Visitor condition show

db/seeds.rb
[] New feature
[] Bug Fix
Checklist:
Link:
=> fix seed path

db/schema.rb
[] New feature
[] Bug Fix
Checklist:
Link:
=> fix schema

Gemfile, Gemfile.lock, app/models/trip.rb, db/schema.rb, db/seeds.rb, spec/models/trip_spec.rb, spec/models/user_spec.rb
__x__ Wrote Tests _x___ Implemented ____ Reviewed
##Closes Waffle Issue  ## no waffle card for this one right?
[] New feature
[] Bug Fix
Checklist:
Link: …
=> fix zip code seeding, validated trip model attributes

app/models/condition.rb, spec/models/condition_spec.rb, spec/models/station_spec.rb
__x__ Wrote Tests __x__ Implemented __x__ Reviewed
##Closes Waffle Issue # no card i don't think...
[] New feature
[] Bug Fix
Checklist:
Link: https://giphy.com/gifs/off-McZdU5M5jpkmk
=> Condition validation

app/views/accessories/index.html.erb, app/views/accessories/show.html.erb, spec/features/visitors/sees_all_accessories_on_bike_shop_spec.rb, spec/features/visitors/sees_attributes_on_accessory_show_spec.rb
##Closes Waffle Issue #15 
[] Bug Fix
Checklist:
Link: http://www.gloucestercitynews.net/.a/6a00d8341bf7d953ef01b7c960caf3970b-320wi
=> Visitor accessory retired show

app/controllers/admin/dashboard_controller.rb, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/models/user.rb, app/views/admin/dashboard/show.html.erb, app/views/layouts/application.html.erb, config/routes.rb, spec/features/visitors/admin_login_spec.rb, spec/models/user_spec.rb
##Closes Waffle Issue   #48 
[] Bug Fix
Checklist:
Link: https://giphy.com/gifs/log-lady-B9bjlOhhqUEdW
=> Admin login

app/controllers/trips_dashboard_controller.rb, app/controllers/tripsdashboard_controller.rb, app/models/trip.rb, app/views/trips_dashboard/index.html.erb, config/routes.rb, spec/features/users/sees_trips_dashboard_spec.rb, spec/models/trip_spec.rb
##Closes Waffle Issue #25 
[] Bug Fix
Checklist:
Link: http://a.fod4.com/misc/Dog%20Smack%20Unexpected.gif
=> User trips dashboard a

app/controllers/admin/base_controller.rb, app/controllers/admin/dashboard_controller.rb, spec/features/visitors/admin_login_spec.rb
##Closes Waffle Issue # no card
[] Bug Fix
Checklist:
Link:
=> Base controller

app/views/trips_dashboard/index.html.erb
=> Development into master

spec/features/users/checkout_workflow_spec.rb
[] Bug Fix
Checklist:
[X] I have commented my code, particularly in hard-to-understand areas
Link:
=> add test for checkout

app/controllers/admin/conditions_controller.rb, app/views/conditions/index.html.erb, app/views/conditions/show.html.erb, config/routes.rb, spec/features/admin/sees_condition_show_spec.rb, spec/features/admin/sees_conditions_index_spec.rb, spec/features/visitors/sees_all_conditions_spec.rb
##Closes Waffle Issue #42  
[] Bug Fix
Checklist:
Link: https://giphy.com/gifs/sleep-ZLxRWG0vhzpiE
=> Admin conditions index delete

app/views/conditions/index.html.erb, config/routes.rb, spec/features/admin/sees_conditions_index_spec.rb, spec/features/visitors/sees_all_conditions_spec.rb
##Closes Waffle Issue #43 
[] Bug Fix
[x] Some Tests have been changed 
* updated user conditions index spec to ensure only admin sees edit and delete buttons
Checklist:
Please Include a link to a gif of your feelings about …
=> Admin conditions index

app/views/conditions/show.html.erb, spec/features/admin/sees_condition_show_spec.rb, spec/features/visitors/sees_attributes_on_condition_show_spec.rb
##Closes Waffle Issue #44 
[] Bug Fix
[x] Some Tests have been changed
* updated visitor sees attributes on condition show spec to ensure only admin sees edit and delete buttons
Checklist:
Please Include a link to a gif of …
=> Admin conditions show

app/controllers/admin/stations_controller.rb, app/controllers/stations_controller.rb, app/models/station.rb, app/views/admin/stations/_form.html.erb, app/views/admin/stations/new.html.erb, config/routes.rb, spec/features/admin/station_new_spec.rb
XWrote Tests XImplemented ____ Reviewed
##Closes Waffle Issue #35 
[] Bug Fix
Checklist:
Link: https://media.giphy.com/media/xiAqCzbB3eZvG/giphy.gif
=> Admin stations new

app/controllers/admin/trips_controller.rb, app/views/admin/trips/edit.html.erb, app/views/trips/index.html.erb, app/views/trips/show.html.erb, spec/features/admin/trip_edit_spec.rb
##Closes Waffle Issue #41 
[] Bug Fix
Checklist:
Link: https://assets.rbl.ms/17037369/980x.gif
=> add tests and functionality for admin edit trips

app/controllers/admin/conditions_controller.rb, app/views/admin/conditions/edit.html.erb, app/views/admin/conditions/new.html.erb, spec/features/admin/condition_edit_spec.rb, spec/features/users/sees_conditions_dashboard_spec.rb
[] Bug Fix
Checklist:
Link: https://giphy.com/gifs/cat-dog-fighting-xBAreNGk5DapO
=> Admin conditions edit

app/controllers/admin/conditions_controller.rb, app/controllers/admin/stations_controller.rb, app/controllers/users_controller.rb, config/routes.rb, spec/features/admin/condition_new_spec.rb, spec/features/admin/station_new_spec.rb, spec/features/users/login_user_spec.rb, spec/features/visitors/create_account_spec.rb
[] Bug Fix
Checklist:
Link:https://media.giphy.com/media/gw3IWyGkC0rsazTi/giphy.gif
=> Test coverage

app/controllers/dashboard_controller.rb, app/controllers/orders_controller.rb, app/models/accessory.rb, app/models/order.rb, app/models/order_accessory.rb, app/models/user.rb, app/views/cart/show.html.erb, app/views/dashboard/show.html.erb, app/views/orders/show.html.erb, config/routes.rb, db/migrate/20180726004852_create_orders.rb, db/migrate/20180726175632_create_order_accessories.rb, db/schema.rb, spec/features/admin/trip_new_spec.rb, spec/features/users/sees_order_show_spec.rb, spec/features/visitors/cart_workflow_spec.rb, spec/models/accessory_spec.rb, spec/models/order_accessory_spec.rb, spec/models/order_spec.rb, spec/models/user_spec.rb
##Closes Waffle Issue #20 
[] Bug Fix
Checklist:
Link: https://vignette.wikia.nocookie.net/legomessageboards/images/b/b6/Funny-gif-Supe …
=> User checkout 2

app/models/station.rb, app/views/stations/show.html.erb
[] New feature
[] Bug Fix
Checklist:
Link:
=> conditional to handle nil cases

app/controllers/dashboard_controller.rb, app/views/dashboard/show.html.erb, config/routes.rb, spec/features/admin/trip_edit_spec.rb, spec/features/admin/trip_new_spec.rb, spec/features/users/checkout_workflow_spec.rb, spec/features/users/sees_order_show_spec.rb
[] Bug Fix
Checklist:
Link: just fixes!
=> fix tests to adhere to updated code

app/controllers/orders_controller.rb, app/views/orders/show.html.erb, spec/features/admin/sees_order_show_spec.rb, spec/models/order_accessory_spec.rb, spec/models/order_spec.rb
##Closes Waffle Issue #49 
[] Bug Fix
Checklist:
Link: http://www.doseoffunny.com/wp-content/uploads/2014/06/funny-kid-gifs-scared-baby …
=> Admin user order show

app/controllers/admin/accessories_controller.rb, app/models/accessory.rb, app/views/accessories/index.html.erb, app/views/accessories/show.html.erb, app/views/admin/accessories/_form.html.erb, app/views/admin/accessories/new.html.erb, config/routes.rb, spec/features/admin/bike_shop_new_spec.rb, spec/models/accessory_spec.rb
XWrote Tests X Implemented ____ Reviewed
[] Bug Fix
Checklist:
Link:
https://giphy.com/gifs/pretty-beautiful-UMRX9R7LBR4Na
=> Admin bike shop new

app/assets/stylesheets/main.scss, app/controllers/admin/accessories_controller.rb, app/views/admin/accessories/_form.html.erb, app/views/admin/accessories/edit.html.erb, app/views/admin/accessories/index.html.erb, app/views/admin/dashboard/show.html.erb, app/views/cart/show.html.erb, config/routes.rb, db/migrate/20180727190015_change_price_in_accessories.rb, db/schema.rb, spec/features/admin/dashboard_a_spec.rb, spec/features/admin/trip_edit_spec.rb
##Closes Waffle Issue #50  
[] Bug Fix
Checklist:
Link: https://giphy.com/gifs/rock-stunt-climbing-NotDYMTH9HUiI
=> Admin dashboard aa

app/controllers/admin/dashboard_controller.rb, app/controllers/admin/orders_controller.rb, app/models/order.rb, app/views/admin/dashboard/index.html.erb, app/views/admin/dashboard/show.html.erb, config/routes.rb, db/seeds.rb, spec/features/admin/admin_dashboard_spec.rb, spec/models/order_spec.rb
XWrote Tests X Implemented ____ Reviewed
##Closes Waffle Issue    #51 
[] Bug Fix
Checklist:
Link:
=> Admin dashboard b

app/views/accessories/index.html.erb, app/views/accessories/show.html.erb, app/views/admin/accessories/edit.html.erb, app/views/admin/accessories/new.html.erb, app/views/admin/conditions/_form.html.erb, app/views/admin/conditions/edit.html.erb, app/views/admin/conditions/new.html.erb, app/views/admin/dashboard/show.html.erb, app/views/admin/stations/_form.html.erb, app/views/admin/stations/edit.html.erb, app/views/admin/stations/new.html.erb, app/views/admin/trips/_form.html.erb, app/views/admin/trips/edit.html.erb, app/views/admin/trips/new.html.erb, app/views/conditions/show.html.erb, app/views/orders/show.html.erb, app/views/stations/show.html.erb, app/views/trips/show.html.erb, spec/features/admin/admin_dashboard_spec.rb, spec/features/admin/condition_edit_spec.rb, spec/features/admin/condition_new_spec.rb, spec/features/admin/sees_order_show_spec.rb, spec/features/admin/station_index_spec.rb, spec/features/admin/station_new_spec.rb, spec/features/admin/station_show_spec.rb, spec/features/admin/trip_edit_spec.rb, spec/features/admin/trip_new_spec.rb, spec/features/users/sees_analysis_on_station_show_spec.rb
[] New feature
[] Bug Fix
[X] Styling
[X] This broke some stuff- but i fixed it
[X] Some Tests have been changed
Checklist:
Link: …
=> In app flow and clean

app/views/admin/dashboard/index.html.erb, app/views/admin/dashboard/show.html.erb, app/views/cart/show.html.erb, app/views/conditions/index.html.erb, app/views/orders/show.html.erb, app/views/stations/index.html.erb, app/views/stations_dashboard/index.html.erb, app/views/trips/index.html.erb, app/views/trips/show.html.erb, app/views/trips_dashboard/index.html.erb, spec/features/admin/admin_dashboard_spec.rb, spec/features/admin/sees_order_show_spec.rb, spec/features/admin/station_index_spec.rb, spec/features/users/checkout_workflow_spec.rb, spec/features/users/sees_order_show_spec.rb
styling and such
all test passing
=> Checkinfollowup

app/views/trips_dashboard/index.html.erb, spec/features/users/sees_trips_dashboard_spec.rb
[] New feature
[X] Bug Fix
Checklist:
Link:
=> fix trip dashboard tests

app/views/accessories/index.html.erb, app/views/admin/dashboard/index.html.erb, app/views/admin/dashboard/show.html.erb, app/views/cart/show.html.erb, app/views/conditions/index.html.erb, app/views/conditions_dashboard/index.html.erb, app/views/orders/show.html.erb, app/views/partials/_nav.html.erb, app/views/stations/index.html.erb, app/views/stations_dashboard/index.html.erb, app/views/trips/index.html.erb
[] New feature
[] Bug Fix
Checklist:
Link:
=> small updates to style consistency

app/controllers/users_controller.rb, app/views/stations/index.html.erb, app/views/stations_dashboard/index.html.erb, config/routes.rb, spec/features/users/login_user_spec.rb, spec/features/users/sees_analysis_on_station_show_spec.rb, spec/features/visitors/create_account_spec.rb
[] New feature
[] Bug Fix
Checklist:
Link:
=> reviewing changes

app/views/cart/show.html.erb, spec/features/visitors/sees_attributes_on_cart_show_spec.rb
Styling
[] New feature
[] Bug Fix
Checklist:
Link:
=> add subtotal to cart show and make checkout a button

app/views/cart/show.html.erb
styling
[] New feature
[] Bug Fix
Checklist:
Link:
=> change cart sub-total to currency

app/views/trips/index.html.erb, spec/features/visitors/cart_workflow_spec.rb
Styling
[] New feature
[] Bug Fix
Checklist:
Link:
=> change trip number by index number on trip index to trip id
